name: miss_shift
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - seaborn=0.12.2
  - scipy=1.10.1
  - matplotlib=3.7.1
  - future=0.18.3
  - numpy=1.24.3
  - scikit-learn=1.2.2
  - tqdm=4.65.0
  - pandas=1.5.3
  - joblib=1.1.1
  - pyyaml=6.0
